version: "3.8"

services:
  api:
    container_name: '${CONTAINER_NAME}-api'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      # Only will build development stage from our dockerfile
      target: development
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "yarn && yarn seed:run && yarn start:debug"
    ports:
      - '${API_PORT_DEV}:${API_PORT_DEV}'
      - '${API_PORT_DEBUG}:${API_PORT_DEBUG}'
    environment:
      WAIT_HOSTS: mysql:${DATABASE_PORT}
    networks:
      - boutique
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 400M

  mysql:
    container_name: '${CONTAINER_NAME}-mysql'
    image: mariadb:10.5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_ROOT_PASSWORD}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_HOST: '${DATABASE_HOST}'
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysqlconfig:/etc/mysql/conf.d
      - ./init/01.sql:/docker-entrypoint-initdb.d/01.sql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    networks:
      - boutique
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 400M

  phpmyadmin:
    container_name: '${CONTAINER_NAME}-phpmyadmin'
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    ports:
      - '${PHP_MYADMIN_PORT}:${PHP_MYADMIN_PORT}'
    depends_on:
      - mysql
    networks:
      - boutique
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1000M
        reservations:
          cpus: '0.5'
          memory: 400M

volumes:
  mysqldata: {}

networks:
  boutique:
